package main

import (
	"bufio"
	"fmt"
	"os"
	"strings"
	//"github.com/PuerkitoBio/goquery"
	//"github.com/fatih/color"
	//"github.com/mattn/go-sqlite3"
)

func ColorUnset() {
}

func ImgSword() {
	image := []string{
		"      ,             ",
		"     //             ",
		"0==={0}>>>>>>>>>>>>>",
		"     \\\\             ",
		"      `             ",
	}
	PrintSlice(image)
}

func ImgINRI() {
	image := []string{
		"              .======.              ",
		"              | INRI |              ",
		"              |      |              ",
		"              |      |              ",
		"     .========'      '========.     ",
		"     |   _      xxxx      _   |     ",
		"     |  /_;-.__ / _\\  _.-;_\\  |     ",
		"     |     `-._`'`_/'`.-'     |     ",
		"     '========.`\\   /`========'     ",
		"              | |  / |              ",
		"              |/-.(  |              ",
		"              |\\_._\\ |              ",
		"              | \\ \\`;|              ",
		"              |  > |/|              ",
		"              | / // |              ",
		"              | |//  |              ",
		"              | \\(\\  |              ",
		"              |  ``  |              ",
		"              |      |              ",
		"              |      |              ",
		"              |      |              ",
		"              |      |              ",
		"  \\\\jgs _  _\\\\| \\//  |//_   _ \\// _ ",
		" ^ `^`^ ^`` `^ ^` ``^^`  `^^` `^ `^ ",
	}
	PrintSlice(image)
}

func PrintSlice(sl []string) {
	for _, st := range sl {
		PrintCenterLines(st)
	}
}

func PrintCenterLines(st string) {
	sl := strings.Split(st, "\n")
	for _, s := range sl {
		PrintCenter(s)
	}
}

func PrintCenterUnknownLines(st string) {
	switch {
	case len(st) > 78:
		sl := strings.SplitAfter(st, " ")
		half := len(sl) / 2
		stBeg := strings.TrimSpace(str(sl[:half]))
		stEnd := strings.TrimSpace(str(sl[half:]))
		PrintCenterUnknownLines(stBeg)
		PrintCenterUnknownLines(stEnd)
	default:
		PrintCenter(st)
	}
}

func PrintCenter(t string) {
	w := 39 - len(t)/2
	s := strings.Repeat(" ", w)
	fmt.Printf("%v%v%v\n", s, t, s)
}

func printRemovedFile(fileName string) {
	Black.Println("Removed", fileName)
}

func Break(s string) {
	fmt.Println(strings.Repeat(s, 79))
}

func Line() {
	Break("-")
}

func BLine() {
	Break("=")
}

func progressTranslation() {
	BLine()
	fmt.Println(transName)
}

func progressBook(title, titleSpacing, numSpacing string, currNum, totalNum int) {
	fmt.Printf("\r=>%v%v%v%d/%d\n",
		title, titleSpacing, numSpacing, currNum, totalNum)
}

func progressChapter(current, total int) {
	fmt.Printf("\r ->%d/%d", current, total)
}

func Input() (answer string) {
	reader := bufio.NewReader(os.Stdin)
	response, _ := reader.ReadString('\n')
	answer = strings.TrimSpace(response)
	return
}

func inputTranslation() (answer string) {
	fmt.Println(
		"No translation specified.",
	)
	fmt.Println(
		"(You can specify the translation by typing 'bgmysword XXX')",
	)
	fmt.Println(
		"Enter the abbreviation of the translation to download",
	)
	fmt.Println(
		"  using the same abbreviation that biblegateway.com uses.",
	)
	fmt.Println(
		"(They're listed at biblegateway.com/versions)",
	)
	fmt.Printf(
		"==> ",
	)
	answer = Input()
	return
}

func copyrightAccept(copyrightInfo, publisherInfo string) {
	Line()
	PrintCenter(
		"License Agreement")
	Line()
	PrintCenter(fmt.Sprintf(
		`This program will generate a MySword bible module for the %v Bible`,
		translation,
	))
	PrintCenter(fmt.Sprintf(
		`by looking up the %v Bible on https://www.biblegateway.org/`,
		translation,
	))
	fmt.Printf("\n")
	PrintCenter(fmt.Sprintf(
		`BibleGateway License for %v`,
		translation,
	))
	PrintCenter(transName)
	PrintCenterUnknownLines(copyrightInfo)
	fmt.Printf("\n")
	PrintCenter(
		"Agreement",
	)
	PrintCenterLines(fmt.Sprintf(
		`  By using this program, I declare that my local copyright law does not forbid
the use of this website for a purpose other than webbrowsing. I will not
distribute any module generated by this program unless explicitely permitted by
%v
I accept full responsibility for all copyright violations that
are the result of using this program and absolve the author of any
responsibility for them.
I understand that I may distribute and/or modify this program itself,
but not any modules generated by it.`,
		publisherInfo,
	))
	PrintCenter(
		"In other words, don't abuse this program.",
	)
	PrintCenter(
		`If you wish to accept the statements above enter the exact word "accept."`,
	)
	PrintCenter(
		"Then press [ENTER]. ",
	)
	fmt.Printf(
		"==> ",
	)
	ansAgree := Input()
	accepted := strings.EqualFold(ansAgree, "accept")
	switch accepted {
	case false:
		fmt.Println("License not accepted.")
		os.Exit(0)
	}
}
